### PR TITLE
Minor updates to gpi_make

### PR DESCRIPTION
**Pull request by borupdaniel**
I haven't tested these but since it's only adding a flag for gpi_make, and will otherwise behave the same, I'd be fine merging this and calling it v1.1.3 – thoughts?

### CODE REVIEW

**Comment by borupdaniel** [comment]
@aganders3 I think the latest commit sets the order of the include and library paths to have the conda libraries first, as we discussed last week.

Can you take a look at this and let me know if you think it's ready to merge? I'd like to get back to testing the core nodes so we can get them up on conda-forge this week if possible!

**Comment by borupdaniel** [comment]
Note I did leave those after anything set in the gpirc file; seems sensible to leave that as the one place a user can override what we've specified if needed.

**Comment by aganders3** [comment]
Thanks - seems good to me. Have you tested locally if this gives the
behavior we want? I’m fine with leaving the user libs first as these
changes are pretty much just for the binary distributions.

**Comment by borupdaniel** [comment]
I tested it locally and it seems like setting both --ignore-system-libs and --ignore-gpirc led to the make not finding any node libraries. I think your implementation was blocking this in the recursive `search_dir` section so I changed that to look in what should be `site-packages` for a conda install if both flags are set. Seems to be working for me now.

**Comment by aganders3** [comment]
This looks good an non-breaking to me if you want to merge for testing on conda-forge

**Pull request merged**
